### ISSUE TITLE
Expanded modding API

### ISSUE THREAD

**Issue by ForLoveOfCats** [ForLoveOfCats/SkyOfSteel#10]
The core modding API *systems* are in place and all current ingame actions are piped to the mod scripts. However the function list needs great expanding.

**Comment by ForLoveOfCats** [comment]
This is now becoming a high priority as 0.1 has shipped.

Please comment suggestions and requests below as to what features are wished from the mod api.

**Comment by RedstoneParadox** [comment]
A few things I'd like to see/work on:

- Functions to place and remove platforms.
- Functions to save and load custom data to and from the save file.
- The ability to expose custom functions to the console (by passing in a high-order function and a name).

**Comment by ForLoveOfCats** [comment]
Yes I was meaning to mention that I need to add a JS type for structures. Save and load should be easy, however the custom functions to the console will be tricky. I have pondered it before and the main issue is that the console engine is never and should never be restarted as that would clear all user defined variables and functions.

**Comment by ForLoveOfCats** [comment]
One way this could be achieved is by storing a list of all functions that the current gamemode has exposed to the console and setting them all to `undefined` when the gamemode is unloaded. (One cannot delete functions in JS)

**Comment by ForLoveOfCats** [comment]
We need a system to execute JS code in the target engine when exposing a type to said engine. Some features the these types must be implemented directly in JS itself (like overriding `.toString`) so this would allow for that.

**Comment by ForLoveOfCats** [comment]
So the new plan is unsandboxed IronPython scripts with explicit manual installation instead of autodownload from server and execute.

Work has begun in the IronPython branch https://github.com/ForLoveOfCats/SkyOfSteel/tree/IronPython

**Comment by ForLoveOfCats** [comment]
Exposing custom functions to the console will be possible now with IronPython as when the gamemode is unloaded we can delete the functions it exposed to the console. (Python allows deleting functions whereas JS does not)

**Comment by ForLoveOfCats** [comment]
Closing this as the game's entire internal API is now exposed with the new C# gamemode scripting
