### ISSUE TITLE
Move to IronPython

### ISSUE THREAD

**Issue by ForLoveOfCats** [ForLoveOfCats/SkyOfSteel#34]
This is just for the todo list

**Comment by Zireael07** [comment]
Why IronPython? IIRC it's discontinued.

**Comment by ForLoveOfCats** [comment]
IronPython is no longer an officially support Microsoft project yes but it is in no way discontinued.

https://github.com/IronLanguages/ironpython2
https://github.com/IronLanguages/ironpython3

**Comment by ForLoveOfCats** [comment]
At any rate IronPython is a more solid solution than Jurassic in terms of bugs/stability, interop with C#, and Python is (imo) a much better language than JavaScript.

**Comment by ForLoveOfCats** [comment]
Done
