### ISSUE TITLE
GUI theme

### ISSUE THREAD

**Issue by ForLoveOfCats** [ForLoveOfCats/SkyOfSteel#41]
The ingame GUI currently uses the default Godot theme. This should be changed.

**Comment by FinnTheTurkey** [comment]
I can do this

**Comment by ForLoveOfCats** [comment]
Done with https://github.com/ForLoveOfCats/SkyOfSteel/pull/47

Needs more work for those little touches which makes a UI stand out but very nice. Scrollbar rendering issue on some systems must be resolved before 0.1.2

**Comment by ForLoveOfCats** [comment]
The scrollbar rendering issue on some machines was resolved by using the default style for the scrollbar grabber.
