### ISSUE TITLE
Gamemode/Mod list in the menu

### ISSUE THREAD

**Issue by Stenodyon** [ForLoveOfCats/SkyOfSteel#59]
It would be helpful to have the list of (successfully loaded) mods and gamemodes in the menu,
to verify their correct installation.

**Comment by ForLoveOfCats** [comment]
When in the game's execution gamemodes are started is going to change later to before the world start in order to allow for custom items as the gamemode has to be loaded for the game to know how to handle custom items in the savegame, so this will likely be part of the save selection screen.

**Comment by ForLoveOfCats** [comment]
Builtin mod support has been removed. Closing due to now being irrelevant
