### ISSUE TITLE
Central Authentication Server

### ISSUE THREAD

**Issue by RedstoneParadox** [ForLoveOfCats/SkyOfSteel#61]
Currently, Sky of Steel does not offer any sort of authentication system to verify your identity. While this is not a problem for playing singleplayer or joining a friend's server. However, people may eventually want to make larger servers and it's harder to moderate servers if there are no accounts to ban/mute/etc. Additionally, any given server requires a way to persistently identify players between sessions in order to store their player data persistently.

I suggest that a central authentication server be created using Azure PlayFab or a similar service and the multiplayer aspect of Sky of Steel should require authentication. Of course, we could also make it so that server owners can disable the auth requirement and just resort to nickname checking if they want.

Side Note: this solve #52

**Comment by ForLoveOfCats** [comment]
With a central account system we can have a friends system, invites, achievements, and more. However at the same time that sort of centralization may be in poor taste for a game such as SkyOfSteel.

The originally planned feature where players can set a password for their player on each server (a la MineTest) could provide a more secure way of ensuring authentication for servers wishing to not use this central system.

**Comment by ForLoveOfCats** [comment]
No longer applicable. https://github.com/ForLoveOfCats/SkyOfSteel/issues/52#issuecomment-631209373

I've always wanted some sort of achievement system, however that would require a central account system. The goal now is to have a per-savefile achievement system similar to Minecraft.
