### ISSUE TITLE
Begin adding audio

### ISSUE THREAD

**Issue by ForLoveOfCats** [ForLoveOfCats/SkyOfSteel#7]
Game currently has zero audio files and/or effects.

**Comment by ForLoveOfCats** [comment]
We currently have a landing sound, wall kick sound, item drop sound, item pickup sound, and menu button mouseover sound. What we really need at the moment is some sort of effects for item placing and destroying. Beyond that, the player land sound and wall kick sound are rather poor in quality and could probably be improved.

**Comment by TdoubleAV** [comment]
Hi
as discussed in discord, I'd like to contribute sound design and maybe music.
so far I see the following SFX:
-  Player/LandSfx.wav
-  Player/WallKickSfx.wav
-  Player/ItemThrowSfx.wav
-  Player/ItemPickupSfx.wav
-  UI/Sfx/ButtomMouseOverSfx.wav

**Comment by ForLoveOfCats** [comment]
Yep, that's all the audio files we currently have

**Comment by ForLoveOfCats** [comment]
I would like to have wind blowing sounds played when the player is traveling at high speed and ramp the volume with the player's speed as well as some background bird noises. Unfortunately I can't seem to make the wind sound loop well and I have no clue how to get decent bird noises which can be cut into individual calls with no background noise suitable for creating a soundscape.

**Comment by ForLoveOfCats** [comment]
We now have a bunch of audio with new sfx being added frequently so I'm closing this as a part of cleaning up the bug list
